const { test, expect } = require("@playwright/test");
const crypto = require("node:crypto");
const fs = require("node:fs/promises");
const path = require("node:path");
const { createGoogleCalendarEvent } = require("../integrations/google");

const DATA_DIR = path.resolve(__dirname, "..", ".tmp", "playwright-data");
const TEST_USER = {
  id: "33333333-3333-4333-8333-333333333333",
  accountId: "acct-pending-payments",
  name: "Payment Tester",
  email: "payment.tester@example.com",
  password: "temporary-password"
};

test.beforeEach(async () => {
  await resetTestData();
});

test("pending payments can be manually confirmed with method and reference", async ({ page }) => {
  await login(page);

  await expect(page.locator("#pendingPaymentsPanel")).toBeVisible();
  await expect(page.locator("#pendingPaymentsList")).toContainText("Alex Rivera");
  await expect(page.locator("#pendingPaymentsList")).toContainText("Overdue");
  const alexPayment = page.locator(".pending-payment-row").filter({ hasText: "Alex Rivera" });
  await alexPayment.getByRole("button", { name: "Mark as paid" }).click();
  await expect(page.locator("#paymentDialog")).toBeVisible();
  await page.locator("#paymentDialog select[name='paymentMethod']").selectOption("Venmo");
  await page.locator("#paymentDialog input[name='paymentReference']").fill("4829301A");
  await page.locator("#paymentDialog").getByRole("button", { name: "Confirm Payment" }).click();
  await expect(page.locator("#paymentDialog")).toBeHidden();

  await expect(page.locator("#jobDetail")).toContainText("Deposit Paid");
  await expect(page.locator("#jobDetail")).toContainText("marked paid");
  await expect(page.locator("#jobDetail")).toContainText("Venmo");
  await expect(page.locator("#jobDetail")).toContainText("4829301A");

  await page.getByRole("button", { name: "Pipeline" }).click();
  await page.getByRole("button", { name: /Alex Rivera/ }).click();
  await page.getByRole("button", { name: "Schedule Job" }).click();
  await expect(page.locator("#scheduleDialog")).toBeVisible();
  await expect(page.locator("#scheduleWeekGrid")).toBeVisible();
  await expect(page.locator("#scheduleWeekGrid")).toContainText("Open");
  await page.locator("#scheduleForm [name='scheduleDate']").fill("2026-06-10");
  await page.locator("#scheduleForm [name='scheduleTime']").fill("09:00");
  await page.locator("#scheduleForm [name='durationHours']").fill("2");
  await page.locator("#scheduleForm").getByRole("button", { name: "Schedule Job", exact: true }).click();
  await expect(page.locator("#scheduleDialog")).toBeHidden();
  await expect(page.locator("#jobDetail")).toContainText("Scheduled");
  await expect(page.locator("#jobDetail")).toContainText("June 10, 2026, 9:00 AM");
  await expect(page.locator("#jobDetail")).not.toContainText("2026-06-10T09:00");

  const jobs = JSON.parse(await fs.readFile(path.join(DATA_DIR, "jobs.json"), "utf8"));
  expect(jobs[0].status).toBe("Scheduled");
  expect(jobs[0].scheduledAt).toBe("2026-06-10T09:00");
  expect(jobs[0].jobDurationMinutes).toBe(120);
  expect(jobs[0].paymentRecords[0]).toMatchObject({
    invoiceType: "deposit",
    source: "manual",
    method: "Venmo",
    reference: "4829301A",
    quickBooksSyncStatus: "pending"
  });
});

test("public deposit and final invoices show configured payment methods", async ({ page }) => {
  await updateTestSettings({
    stripeSecretKey: "sk_test_invoice_display_only",
    zellePayment: "owner@johnson.test",
    cashAppPayment: "$JohnsonExterior",
    venmoPayment: "@JohnsonExterior",
    paymentInstructions: "Please include the invoice number in the payment note."
  });

  await page.goto("/invoice/44444444-4444-4444-8444-444444444444?type=deposit&token=pf-deposit-test");
  await expect(page.getByRole("heading", { name: "Deposit Invoice" })).toBeVisible();
  await expect(page.locator(".doc__logo")).toBeVisible();
  await expect(page.locator("body")).not.toContainText("Payment options available");
  await expect(page.locator("body")).toContainText("Johnson Exterior Cleaning");
  await expect(page.locator("body")).toContainText("owner@johnson.test | (555) 222-3333");
  await expect(page.locator("body")).toContainText("Zelle");
  await expect(page.locator("body")).toContainText("owner@johnson.test");
  await expect(page.locator("body")).toContainText("Cash App");
  await expect(page.locator("body")).toContainText("$JohnsonExterior");
  await expect(page.locator("body")).toContainText("Venmo");
  await expect(page.locator("body")).toContainText("@JohnsonExterior");
  await expect(page.locator("body")).toContainText("Please include the invoice number in the payment note.");
  await expect(page.getByRole("button", { name: "Pay by Credit Card" })).toBeVisible();
  await expect(page.locator("body")).toContainText("This secure customer page is generated by PressureFlow for Johnson Exterior Cleaning.");
  await expect(page.locator("body")).not.toContainText("Payment options have not been configured yet.");

  await page.goto("/invoice/55555555-5555-4555-8555-555555555555?type=final&token=pf-final-test");
  await expect(page.getByRole("heading", { name: "Final Invoice" })).toBeVisible();
  await expect(page.locator("body")).toContainText("Zelle");
  await expect(page.locator("body")).toContainText("Cash App");
  await expect(page.locator("body")).toContainText("Venmo");
  await expect(page.getByRole("button", { name: "Pay by Credit Card" })).toBeVisible();
  await expect(page.locator("body")).not.toContainText("Payment options have not been configured yet.");
});

test("paid public invoices show a paid state without payment CTAs", async ({ page }) => {
  await updateStoredJob("44444444-4444-4444-8444-444444444444", {
    squareDepositInvoiceStatus: "PAID",
    squareDepositPaidAt: "2026-06-12T12:00:00.000Z"
  });
  await updateTestSettings({
    stripeSecretKey: "sk_test_invoice_display_only",
    zellePayment: "owner@johnson.test"
  });

  await page.goto("/invoice/44444444-4444-4444-8444-444444444444?type=deposit&token=pf-deposit-test");
  await expect(page.getByRole("heading", { name: "Deposit Invoice" })).toBeVisible();
  await expect(page.locator("body")).toContainText("Payment received");
  await expect(page.locator("body")).toContainText("No further payment is due for this invoice.");
  await expect(page.getByRole("button", { name: "Pay by Credit Card" })).toHaveCount(0);
  await expect(page.locator("body")).not.toContainText("Zelle");
});

test("public deposit and final invoices show contact fallback when no payment methods are configured", async ({ page }) => {
  await page.goto("/invoice/44444444-4444-4444-8444-444444444444?type=deposit&token=pf-deposit-test");
  await expect(page.getByRole("heading", { name: "Deposit Invoice" })).toBeVisible();
  await expect(page.locator("body")).not.toContainText("Payment instructions pending");
  await expect(page.locator("body")).not.toContainText("Secure payment options");
  await expect(page.locator("body")).toContainText("Payment options have not been configured yet. Please contact Johnson Exterior Cleaning at owner@johnson.test or (555) 222-3333 for payment instructions.");
  await expect(page.locator("body")).not.toContainText("Payment instructions will be provided by the business.");
  await expect(page.getByRole("button", { name: "Pay by Credit Card" })).toHaveCount(0);

  await page.goto("/invoice/55555555-5555-4555-8555-555555555555?type=final&token=pf-final-test");
  await expect(page.getByRole("heading", { name: "Final Invoice" })).toBeVisible();
  await expect(page.locator("body")).toContainText("Payment options have not been configured yet. Please contact Johnson Exterior Cleaning at owner@johnson.test or (555) 222-3333 for payment instructions.");
  await expect(page.locator("body")).not.toContainText("Payment instructions will be provided by the business.");
  await expect(page.getByRole("button", { name: "Pay by Credit Card" })).toHaveCount(0);
});

test("public invoice renders manual payment instructions without card CTA", async ({ page }) => {
  await updateTestSettings({
    paymentInstructions: "Please pay by check at the service address and include invoice number PPW-D-TEST."
  });

  await page.goto("/invoice/44444444-4444-4444-8444-444444444444?type=deposit&token=pf-deposit-test");
  await expect(page.getByRole("heading", { name: "Deposit Invoice" })).toBeVisible();
  await expect(page.locator("body")).not.toContainText("Payment options available");
  await expect(page.locator("body")).toContainText("Please pay by check at the service address and include invoice number PPW-D-TEST.");
  await expect(page.locator("body")).not.toContainText("Payment options have not been configured yet.");
  await expect(page.getByRole("button", { name: "Pay by Credit Card" })).toHaveCount(0);
});

test("contractor is blocked before sending deposit invoice when no payment methods are configured", async ({ page }) => {
  await login(page);

  await page.getByRole("button", { name: "Pipeline" }).click();
  await page.getByRole("button", { name: /Contract Carla/ }).click();
  await expect(page.locator("#jobDetail")).toContainText("Deposit Invoice");
  await expect(page.locator("#jobDetail")).toContainText("Payment options are not configured yet. Customers will not have a clear way to pay this invoice.");
  await expect(page.locator("#jobDetail")).toContainText("Configure payment options");

  page.once("dialog", async (dialog) => {
    expect(dialog.message()).toContain("Payment options are not configured yet. Customers will not have a clear way to pay this invoice.");
    await dialog.accept();
  });
  await page.getByRole("button", { name: "Send by Email" }).first().click();
  await expect(page.locator("#jobDetail")).toContainText("Contract Signed");

  const jobs = JSON.parse(await fs.readFile(path.join(DATA_DIR, "jobs.json"), "utf8"));
  const carla = jobs.find((item) => item.id === "66666666-6666-4666-8666-666666666666");
  expect(carla.status).toBe("Contract Signed");
  expect(carla.squareDepositInvoiceId || "").toBe("");
});

test("zero percent deposit skips deposit invoice and moves signed contract to scheduling", async ({ page }) => {
  await login(page);

  await page.getByRole("button", { name: "Pipeline" }).click();
  await page.getByRole("button", { name: /Zero Deposit Zoe/ }).click();
  await expect(page.locator("#jobDetail")).toContainText("Contract Signed");
  await expect(page.locator("#jobDetail")).toContainText("$0.00");
  await expect(page.getByRole("button", { name: "Schedule Job" })).toBeVisible();
  await expect(page.locator("#jobDetail")).not.toContainText("Deposit Invoice");

  await page.getByRole("button", { name: "Schedule Job" }).click();
  await expect(page.locator("#scheduleDialog")).toBeVisible();

  const jobs = JSON.parse(await fs.readFile(path.join(DATA_DIR, "jobs.json"), "utf8"));
  const zoe = jobs.find((item) => item.id === "88888888-8888-4888-8888-888888888888");
  expect(zoe.status).toBe("Contract Signed");
  expect(zoe.squareDepositInvoiceId || "").toBe("");
});

test("zero percent deposit keeps public contract and final invoice at full balance", async ({ page }) => {
  await updateTestSettings({
    paymentInstructions: "Please pay the final balance after completion."
  });
  await updateStoredJob("88888888-8888-4888-8888-888888888888", {
    status: "Completed",
    contractApprovalToken: "zero-contract-token",
    contractApprovalUrl: "http://127.0.0.1:3173/contract/88888888-8888-4888-8888-888888888888?token=zero-contract-token"
  });

  await page.goto("/contract/88888888-8888-4888-8888-888888888888?token=zero-contract-token");
  await expect(page.getByRole("row", { name: /Deposit \$0\.00 \(0%\)/ })).toBeVisible();
  await expect(page.locator("body")).toContainText("Deposit Due Before Scheduling$0.00");
  await expect(page.locator("body")).toContainText("Final Balance After Completion$350.00");
  await expect(page.locator("body")).not.toContainText("(25%)");

  await login(page);
  const sessionResponse = await page.request.get("/api/session");
  expect(sessionResponse.ok()).toBeTruthy();
  const session = await sessionResponse.json();
  const invoice = await page.request.post("/api/jobs/88888888-8888-4888-8888-888888888888/send-final-invoice-text", {
    headers: { "x-csrf-token": session.csrfToken },
    data: {}
  });
  const invoicePayload = await invoice.json();
  expect(invoice.ok(), JSON.stringify(invoicePayload)).toBeTruthy();
  expect(invoicePayload.job.squareDepositInvoiceId || "").toBe("");
  expect(invoicePayload.job.squareFinalInvoiceUrl).toBeTruthy();

  await page.goto(invoicePayload.job.squareFinalInvoiceUrl);
  await expect(page.getByRole("heading", { name: "Final Invoice" })).toBeVisible();
  await expect(page.getByRole("row", { name: /Final balance after deposit \$350\.00/ })).toBeVisible();
  await expect(page.locator("body")).not.toContainText("Deposit (25%)");
});

test("schedule dialog blocks overlapping job times", async ({ page }) => {
  await updateStoredJob("66666666-6666-4666-8666-666666666666", {
    status: "Scheduled",
    scheduledAt: "2026-06-10T10:00",
    jobDurationMinutes: 180
  });

  await login(page);
  await page.getByRole("button", { name: "Pipeline" }).click();
  await page.getByRole("button", { name: /Zero Deposit Zoe/ }).click();
  await page.getByRole("button", { name: "Schedule Job" }).click();
  await expect(page.locator("#scheduleDialog")).toBeVisible();
  await page.locator("#scheduleForm [name='scheduleDate']").fill("2026-06-10");
  await page.locator("#scheduleForm [name='scheduleTime']").fill("10:30");
  await page.locator("#scheduleForm [name='durationHours']").fill("2");
  await page.locator("#scheduleForm").getByRole("button", { name: "Schedule Job", exact: true }).click();
  await expect(page.locator("#scheduleDialog")).toBeVisible();
  await expect(page.locator("#scheduleConflictStatus")).toContainText("Already booked: Contract Carla");

  const jobs = JSON.parse(await fs.readFile(path.join(DATA_DIR, "jobs.json"), "utf8"));
  const zoe = jobs.find((item) => item.id === "88888888-8888-4888-8888-888888888888");
  expect(zoe.status).toBe("Contract Signed");
});

test("calendar setup, auth, and event failures expose structured scheduling errors", async () => {
  const job = baseScheduleJob();

  await expect(createGoogleCalendarEvent({
    googleClientId: "client",
    googleClientSecret: "secret",
    googleRedirectUri: "https://example.com/auth/google/callback"
  }, job, "2026-06-10T09:00", 120)).rejects.toMatchObject({
    statusCode: 409,
    code: "GOOGLE_CALENDAR_NOT_CONFIGURED",
    exposeToClient: true
  });

  const originalFetch = global.fetch;
  try {
    global.fetch = async () => ({
      ok: false,
      json: async () => ({ error: "invalid_grant" })
    });
    await expect(createGoogleCalendarEvent({
      googleClientId: "client",
      googleClientSecret: "secret",
      googleRedirectUri: "https://example.com/auth/google/callback",
      googleRefreshToken: "expired-token"
    }, job, "2026-06-10T09:00", 120)).rejects.toMatchObject({
      statusCode: 409,
      code: "GOOGLE_CALENDAR_AUTH_REVOKED",
      exposeToClient: true
    });

    let requestCount = 0;
    global.fetch = async () => {
      requestCount += 1;
      if (requestCount === 1) {
        return { ok: true, json: async () => ({ access_token: "access-token" }) };
      }
      return {
        ok: false,
        status: 403,
        json: async () => ({ error: { message: "Calendar API has not been used in project." } })
      };
    };
    await expect(createGoogleCalendarEvent({
      googleClientId: "client",
      googleClientSecret: "secret",
      googleRedirectUri: "https://example.com/auth/google/callback",
      googleRefreshToken: "connected-token"
    }, job, "2026-06-10T09:00", 120)).rejects.toMatchObject({
      statusCode: 502,
      code: "GOOGLE_CALENDAR_EVENT_CREATE_FAILED",
      exposeToClient: true
    });
  } finally {
    global.fetch = originalFetch;
  }
});

test("calendar reschedule updates existing events and recreates stale event ids", async () => {
  const originalFetch = global.fetch;
  const settings = {
    googleClientId: "client",
    googleClientSecret: "secret",
    googleRedirectUri: "https://example.com/auth/google/callback",
    googleRefreshToken: "connected-token"
  };

  try {
    const updateRequests = [];
    global.fetch = async (url, options = {}) => {
      updateRequests.push({ url: String(url), method: options.method || "GET" });
      if (String(url).includes("/token")) {
        return { ok: true, json: async () => ({ access_token: "access-token" }) };
      }
      return {
        ok: true,
        json: async () => ({ id: "existing-event", htmlLink: "https://calendar.example/existing-event" })
      };
    };

    const updated = await createGoogleCalendarEvent({
      ...settings,
      googleCalendarId: "primary"
    }, {
      ...baseScheduleJob(),
      googleCalendarEventId: "existing-event"
    }, "2026-06-10T09:00", 120);

    expect(updated).toMatchObject({ id: "existing-event" });
    expect(updateRequests.some((request) => request.method === "PATCH" && request.url.includes("/events/existing-event"))).toBeTruthy();

    const staleRequests = [];
    global.fetch = async (url, options = {}) => {
      staleRequests.push({ url: String(url), method: options.method || "GET" });
      if (String(url).includes("/token")) {
        return { ok: true, json: async () => ({ access_token: "access-token" }) };
      }
      if ((options.method || "GET") === "PATCH") {
        return {
          ok: false,
          status: 404,
          json: async () => ({ error: { message: "Not found" } })
        };
      }
      return {
        ok: true,
        json: async () => ({ id: "replacement-event", htmlLink: "https://calendar.example/replacement-event" })
      };
    };

    const recreated = await createGoogleCalendarEvent({
      ...settings,
      googleCalendarId: "primary"
    }, {
      ...baseScheduleJob(),
      googleCalendarEventId: "stale-event"
    }, "2026-06-11T13:30", 90);

    expect(recreated).toMatchObject({ id: "replacement-event" });
    expect(staleRequests.some((request) => request.method === "PATCH" && request.url.includes("/events/stale-event"))).toBeTruthy();
    expect(staleRequests.some((request) => request.method === "POST" && request.url.includes("/events"))).toBeTruthy();
  } finally {
    global.fetch = originalFetch;
  }
});

test("schedule action route returns structured JSON for malformed payload and missing jobs", async ({ page }) => {
  await login(page);
  const sessionResponse = await page.request.get("/api/session");
  expect(sessionResponse.ok()).toBeTruthy();
  const session = await sessionResponse.json();

  const malformed = await page.request.post("/api/jobs/88888888-8888-4888-8888-888888888888/schedule", {
    headers: { "x-csrf-token": session.csrfToken },
    data: { scheduledAt: "not-a-date", jobDurationMinutes: 120 }
  });
  expect(malformed.status()).toBe(400);
  expect(malformed.headers()["content-type"]).toContain("application/json");
  await expect(malformed.json()).resolves.toEqual({ error: "Schedule date/time must be a real date and time." });

  const missing = await page.request.post("/api/jobs/missing-schedule-job/schedule", {
    headers: { "x-csrf-token": session.csrfToken },
    data: { scheduledAt: "2026-06-10T09:00", jobDurationMinutes: 120 }
  });
  expect(missing.status()).toBe(404);
  expect(missing.headers()["content-type"]).toContain("application/json");
  await expect(missing.json()).resolves.toEqual({ error: "Job not found." });
});

test("scheduled jobs can be rescheduled without an existing calendar event id", async ({ page }) => {
  await updateStoredJob("88888888-8888-4888-8888-888888888888", {
    status: "Scheduled",
    scheduledAt: "2026-06-10T09:00",
    scheduledEventAt: "2026-06-01T12:00:00.000Z",
    jobDurationMinutes: 120,
    googleCalendarEventId: "",
    googleCalendarEventUrl: ""
  });

  await login(page);
  await page.getByRole("button", { name: "Pipeline" }).click();
  await page.getByRole("button", { name: /Zero Deposit Zoe/ }).click();
  await expect(page.getByRole("button", { name: "Reschedule Job" })).toBeVisible();

  await page.getByRole("button", { name: "Reschedule Job" }).click();
  await expect(page.locator("#scheduleDialog")).toBeVisible();
  await expect(page.locator("#scheduleForm [name='scheduleDate']")).toHaveValue("2026-06-10");
  await expect(page.locator("#scheduleForm [name='scheduleTime']")).toHaveValue("09:00");

  await page.locator("#scheduleForm [name='scheduleDate']").fill("2026-06-11");
  await page.locator("#scheduleForm [name='scheduleTime']").fill("13:30");
  await page.locator("#scheduleForm [name='durationHours']").fill("1.5");
  await page.locator("#scheduleForm").getByRole("button", { name: "Schedule Job", exact: true }).click();

  await expect(page.locator("#scheduleDialog")).toBeHidden();
  await expect(page.locator("#jobDetail")).toContainText("Scheduled");
  await expect(page.locator("#jobDetail")).toContainText("June 11, 2026, 1:30 PM");

  const jobs = JSON.parse(await fs.readFile(path.join(DATA_DIR, "jobs.json"), "utf8"));
  const zoe = jobs.find((item) => item.id === "88888888-8888-4888-8888-888888888888");
  expect(zoe.status).toBe("Scheduled");
  expect(zoe.scheduledAt).toBe("2026-06-11T13:30");
  expect(zoe.jobDurationMinutes).toBe(90);
});

test("frontend displays structured scheduling failures without a false success toast", async ({ page }) => {
  await login(page);

  await page.route("**/api/jobs/88888888-8888-4888-8888-888888888888/schedule", async (route) => {
    await route.fulfill({
      status: 409,
      contentType: "application/json",
      body: JSON.stringify({ error: "Google Calendar is not connected yet. Open Settings and click Connect Google Calendar." })
    });
  });

  await page.getByRole("button", { name: "Pipeline" }).click();
  await page.getByRole("button", { name: /Zero Deposit Zoe/ }).click();
  await page.getByRole("button", { name: "Schedule Job" }).click();
  await expect(page.locator("#scheduleDialog")).toBeVisible();
  await page.locator("#scheduleForm [name='scheduleDate']").fill("2026-06-10");
  await page.locator("#scheduleForm [name='scheduleTime']").fill("09:00");
  await page.locator("#scheduleForm [name='durationHours']").fill("2");
  await page.locator("#scheduleForm").getByRole("button", { name: "Schedule Job", exact: true }).click();

  await expect(page.locator(".workflow-action-status.error")).toContainText("Google Calendar is not connected yet.");
  await expect(page.locator("#jobDetail")).toContainText("Contract Signed");
  await expect(page.locator(".toast").filter({ hasText: "Job scheduled" })).toHaveCount(0);
});

test("frontend displays specific reschedule failures instead of generic not found", async ({ page }) => {
  await updateStoredJob("88888888-8888-4888-8888-888888888888", {
    status: "Scheduled",
    scheduledAt: "2026-06-10T09:00",
    scheduledEventAt: "2026-06-01T12:00:00.000Z",
    jobDurationMinutes: 120,
    googleCalendarEventId: "stale-event"
  });

  await login(page);

  await page.route("**/api/jobs/88888888-8888-4888-8888-888888888888/schedule", async (route) => {
    await route.fulfill({
      status: 409,
      contentType: "application/json",
      body: JSON.stringify({ error: "Google Calendar calendar was not found. Open Settings and confirm the Calendar ID or reconnect Google Calendar." })
    });
  });

  await page.getByRole("button", { name: "Pipeline" }).click();
  await page.getByRole("button", { name: /Zero Deposit Zoe/ }).click();
  await page.getByRole("button", { name: "Reschedule Job" }).click();
  await expect(page.locator("#scheduleDialog")).toBeVisible();
  await page.locator("#scheduleForm [name='scheduleDate']").fill("2026-06-11");
  await page.locator("#scheduleForm [name='scheduleTime']").fill("13:30");
  await page.locator("#scheduleForm [name='durationHours']").fill("1.5");
  await page.locator("#scheduleForm").getByRole("button", { name: "Schedule Job", exact: true }).click();

  await expect(page.locator(".workflow-action-status.error")).toContainText("Google Calendar calendar was not found.");
  await expect(page.locator(".workflow-action-status.error")).not.toHaveText("Not found");
  await expect(page.locator("#jobDetail")).toContainText("Scheduled");
  await expect(page.locator(".toast").filter({ hasText: /Job (scheduled|rescheduled)/ })).toHaveCount(0);
});

test("contractor is blocked before sending final invoice when no payment methods are configured", async ({ page }) => {
  await login(page);

  await page.getByRole("button", { name: "Pipeline" }).click();
  await page.getByRole("button", { name: /Completed Casey/ }).click();
  await expect(page.locator("#jobDetail")).toContainText("Final Invoice");
  page.once("dialog", async (dialog) => {
    expect(dialog.message()).toContain("Payment options are not configured yet. Customers will not have a clear way to pay this invoice.");
    await dialog.accept();
  });
  await page.getByRole("button", { name: "Send by Email" }).first().click();
  await expect(page.locator("#jobDetail")).toContainText("Completed");

  const jobs = JSON.parse(await fs.readFile(path.join(DATA_DIR, "jobs.json"), "utf8"));
  const casey = jobs.find((item) => item.id === "77777777-7777-4777-8777-777777777777");
  expect(casey.status).toBe("Completed");
  expect(casey.squareFinalInvoiceId || "").toBe("");
});

test("dashboard setup reminder opens payment settings when payment methods are missing", async ({ page }) => {
  await login(page);

  await expect(page.locator("#dashboardPaymentSetupPanel")).toBeVisible();
  await expect(page.locator("#dashboardPaymentSetupPanel")).toContainText("Set up payment options before sending invoices.");
  await page.locator("#dashboardPaymentSetupPanel").getByRole("button", { name: "Configure payment options" }).click();
  await expect(page.locator("#settingsDialog")).toBeVisible();
  await expect(page.locator("#settingsPaymentSection input[name='zellePayment']")).toBeFocused();
});

async function login(page) {
  await page.goto("/login");
  await page.getByLabel("Email").fill(TEST_USER.email);
  await page.getByLabel("Password").fill(TEST_USER.password);
  await page.getByRole("button", { name: "Sign In" }).click();
  await expect(page.locator("#sidebarBusinessName")).toHaveText("Johnson Exterior Cleaning");
}

async function updateTestSettings(partial) {
  const usersPath = path.join(DATA_DIR, "users.json");
  const users = JSON.parse(await fs.readFile(usersPath, "utf8"));
  users[0].settings = {
    ...users[0].settings,
    ...partial
  };
  await fs.writeFile(usersPath, JSON.stringify(users, null, 2));
}

async function updateStoredJob(jobId, partial) {
  const jobsPath = path.join(DATA_DIR, "jobs.json");
  const jobs = JSON.parse(await fs.readFile(jobsPath, "utf8"));
  const job = jobs.find((item) => item.id === jobId);
  Object.assign(job, partial);
  await fs.writeFile(jobsPath, JSON.stringify(jobs, null, 2));
}

function baseScheduleJob() {
  return {
    id: "schedule-unit-job",
    customerName: "Schedule Tester",
    email: "schedule@example.com",
    phone: "(555) 111-2222",
    address: "100 Main Street, Riverside, CA 92501",
    serviceType: "Driveway cleaning",
    estimate: 250,
    depositPercent: 25,
    lineItems: [{ name: "Driveway cleaning", quantity: 1, unit: "QTY", total: 250 }]
  };
}

async function resetTestData() {
  await fs.rm(DATA_DIR, { recursive: true, force: true });
  await fs.mkdir(DATA_DIR, { recursive: true });
  await fs.writeFile(path.join(DATA_DIR, "expenses.json"), "[]");
  await fs.writeFile(path.join(DATA_DIR, "customers.json"), "[]");
  await fs.writeFile(path.join(DATA_DIR, "webhook-events.json"), "[]");
  await fs.writeFile(path.join(DATA_DIR, "accounts.json"), JSON.stringify([{
    id: TEST_USER.accountId,
    name: "Pending Payments Test Account",
    plan: "tester",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }], null, 2));
  await fs.writeFile(path.join(DATA_DIR, "users.json"), JSON.stringify([{
    id: TEST_USER.id,
    accountId: TEST_USER.accountId,
    name: TEST_USER.name,
    email: TEST_USER.email,
    passwordHash: hashPassword(TEST_USER.password),
    role: "tester",
    disabled: false,
    settings: {
      businessName: "Johnson Exterior Cleaning",
      businessEmail: "owner@johnson.test",
      businessPhone: "(555) 222-3333",
      businessLogoDataUrl: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==",
      serviceIndustry: "Pressure Washing",
      onboardingCompleted: true,
      paymentFollowUpHours: 24
    },
    lastLoginAt: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }], null, 2));
  await fs.writeFile(path.join(DATA_DIR, "settings.local.json"), JSON.stringify({
    businessName: "",
    businessEmail: "",
    businessPhone: "",
    onboardingCompleted: false,
    customServices: [],
    customServiceTypes: [],
    customPhotoSections: [],
    customTemplates: []
  }, null, 2));
  await fs.writeFile(path.join(DATA_DIR, "jobs.json"), JSON.stringify([{
    id: "44444444-4444-4444-8444-444444444444",
    accountId: TEST_USER.accountId,
    customerName: "Alex Rivera",
    email: "alex@example.com",
    phone: "(555) 444-1212",
    streetAddress: "100 Main Street",
    city: "Riverside",
    state: "CA",
    zip: "92501",
    address: "100 Main Street, Riverside, CA 92501",
    serviceType: "Driveway cleaning",
    estimate: 200,
    depositPercent: 25,
    lineItems: [{ name: "Driveway cleaning", quantity: 1, unit: "QTY", total: 200 }],
    status: "Deposit Sent",
    squareDepositInvoiceId: "pf-deposit-test",
    squareDepositInvoiceUrl: "http://127.0.0.1:3173/invoice/44444444-4444-4444-8444-444444444444?type=deposit&token=pf-deposit-test",
    paymentRecords: [],
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-06-01T12:00:00.000Z"
  }, {
    id: "55555555-5555-4555-8555-555555555555",
    accountId: TEST_USER.accountId,
    customerName: "Final Finn",
    email: "finn@example.com",
    phone: "(555) 555-1212",
    streetAddress: "200 Oak Street",
    city: "Riverside",
    state: "CA",
    zip: "92501",
    address: "200 Oak Street, Riverside, CA 92501",
    serviceType: "Patio cleaning",
    estimate: 300,
    depositPercent: 25,
    lineItems: [{ name: "Patio cleaning", quantity: 1, unit: "QTY", total: 300 }],
    status: "Final Invoice Sent",
    squareFinalInvoiceId: "pf-final-test",
    squareFinalInvoiceUrl: "http://127.0.0.1:3173/invoice/55555555-5555-4555-8555-555555555555?type=final&token=pf-final-test",
    paymentRecords: [],
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-06-01T12:00:00.000Z"
  }, {
    id: "66666666-6666-4666-8666-666666666666",
    accountId: TEST_USER.accountId,
    customerName: "Contract Carla",
    email: "carla@example.com",
    phone: "(555) 666-1212",
    streetAddress: "300 Pine Street",
    city: "Riverside",
    state: "CA",
    zip: "92501",
    address: "300 Pine Street, Riverside, CA 92501",
    serviceType: "House wash",
    estimate: 400,
    depositPercent: 25,
    lineItems: [{ name: "House wash", quantity: 1, unit: "QTY", total: 400 }],
    status: "Contract Signed",
    paymentRecords: [],
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-06-01T12:00:00.000Z"
  }, {
    id: "88888888-8888-4888-8888-888888888888",
    accountId: TEST_USER.accountId,
    customerName: "Zero Deposit Zoe",
    email: "zoe@example.com",
    phone: "(555) 888-1212",
    streetAddress: "500 Zero Street",
    city: "Riverside",
    state: "CA",
    zip: "92501",
    address: "500 Zero Street, Riverside, CA 92501",
    serviceType: "Pool deck cleaning",
    estimate: 350,
    depositPercent: 0,
    lineItems: [{ name: "Pool deck cleaning", quantity: 1, unit: "QTY", total: 350 }],
    status: "Contract Signed",
    paymentRecords: [],
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-06-01T12:00:00.000Z"
  }, {
    id: "77777777-7777-4777-8777-777777777777",
    accountId: TEST_USER.accountId,
    customerName: "Completed Casey",
    email: "casey@example.com",
    phone: "(555) 777-1212",
    streetAddress: "400 Elm Street",
    city: "Riverside",
    state: "CA",
    zip: "92501",
    address: "400 Elm Street, Riverside, CA 92501",
    serviceType: "Fence cleaning",
    estimate: 500,
    depositPercent: 25,
    lineItems: [{ name: "Fence cleaning", quantity: 1, unit: "QTY", total: 500 }],
    status: "Completed",
    paymentRecords: [],
    createdAt: "2026-06-01T12:00:00.000Z",
    updatedAt: "2026-06-01T12:00:00.000Z"
  }], null, 2));
}

function hashPassword(password) {
  const iterations = 120000;
  const salt = "playwright-local-salt";
  const hash = crypto.pbkdf2Sync(String(password || ""), salt, iterations, 32, "sha256").toString("base64url");
  return `pbkdf2-sha256$${iterations}$${salt}$${hash}`;
}
